name: Quality-Check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  quality-check:
    name: Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test:ci
